version: "3"

services:

  zookeeper:
    image: liubaozhu/zookeeper
    #depends_on:
    # - ubuntu
    # build: .
    ports:
      - 2181:2181
    volumes:
      - /data/zookeeper:/tmp/zookeeper
    command: ["sh", "-c", "/home/zookeeper/start.sh"]